apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: web
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
